language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.402
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
after_success:
  - ./scripts/dotnet-pack.sh
notifications:
  email:
    on_success: never
    on_failure: always